on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: version
        run: echo "::set-output name=version::$(./target/debug/qr_gen --version)"
        id: version

      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
        
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/debug/qr_gen
          asset_name: qr_gen.linux-amd64
          asset_content_type: application/executable
